#!/usr/bin/env sh

PADDINGS=3 # All paddings use this value (icon, label, background)
POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11
SHADOW=on
FONT=GeistMono

# Color Palette
BLACK=0xff181926
WHITE=0xffcad3f5
RED=0xffed8796
GREEN=0xffa6da95
BLUE=0xff8aadf4
YELLOW=0xffeed49f
ORANGE=0xfff5a97f
MAGENTA=0xffc6a0f6
GREY=0xff939ab7
TRANSPARENT=0x00000000

BAR_COLOR=0xcc24273a #$GREY # Grey bar
ICON_COLOR=$WHITE    # Color of all icons
LABEL_COLOR=$WHITE   # Color of all labels
POPUP_BACKGROUND_COLOR=$BLACK
POPUP_BORDER_COLOR=$WHITE
SHADOW_COLOR=$BLACK

sketchybar \
  --bar height=32 \
  color=0xFF000000 \
  shadow=$SHADOW \
  position=top \
  sticky=on \
  padding_right=18 \
  padding_left=18 \
  blur_radius=20 \
  display=main \
  --default updates=when_shown \
  icon.font="$FONT:Bold:14.0" \
  icon.color=$ICON_COLOR \
  icon.padding_left=$PADDINGS \
  icon.padding_right=$PADDINGS \
  label.font="$FONT:Semibold:13.0" \
  label.color=$LABEL_COLOR \
  label.padding_left=$PADDINGS \
  label.padding_right=$PADDINGS \
  background.padding_right=$PADDINGS \
  background.padding_left=$PADDINGS \
  popup.background.border_width=2 \
  popup.background.corner_radius=11 \
  popup.background.border_color=$POPUP_BORDER_COLOR \
  popup.background.color=$POPUP_BACKGROUND_COLOR \
  popup.background.shadow.drawing=$SHADOW

sketchybar --add event aerospace_workspace_change

RED=0xffed8796
for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item "space.$sid" left \
    --subscribe "space.$sid" aerospace_workspace_change \
    --set "space.$sid" \
    icon="$sid" \
    icon.padding_left=$PADDINGS \
    icon.padding_right=$PADDINGS \
    label.padding_right=$PADDINGS \
    icon.highlight_color=$RED \
    background.color=0x44ffffff \
    background.corner_radius=3 \
    background.height=16 \
    background.drawing=off \
    label.font="$FONT:Regular:16.0" \
    label.background.height=16 \
    label.background.drawing=on \
    label.background.color=0xff494d64 \
    label.background.corner_radius=3 \
    label.drawing=off \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

sketchybar --update
